#thresholds for determining whether a note was played
V_THRESH = 122
BLACK_V_THRESH = 147
DEPTH_THRESH = -100
NOTE_WIDTH = 25
X_MIN = -200
X_MAX = 200
BLACK_NOTE_WIDTH = 20
FRONT_THRESH = -20
ADJUST_V_THRESH = 5

#GUI Constants
SCALE_X = 3
SCALE_Y = 3
SCALE_Y_BOTTOM = 1.5

